### ISSUE TITLE
Segmentation fault when "Open with" option is selected in some files

### ISSUE THREAD

**Issue by alexoj** [mate-desktop/engrampa#126]
GDB backtrace follows:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5d3ee52 in __strcmp_sse2_unaligned () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5d3ee52 in __strcmp_sse2_unaligned () from /usr/lib/libc.so.6
#1  0x0000000000418e80 in dlg_open_with (window=0x6b1260, file_list=file_list@entry=0xcde960) at dlg-open-with.c:417
#2  0x0000000000438de3 in fr_window_open_extracted_files (odata=0xce5ca0) at fr-window.c:8456
#3  fr_window_open_files__extract_done_cb (archive=<optimized out>, action=<optimized out>, error=<optimized out>,
    callback_data=0xce5ca0) at fr-window.c:8527
#4  0x00007ffff688b015 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff689d061 in ?? () from /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff68a5dfc in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff68a612f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff688b015 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff689d061 in ?? () from /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff68a5dfc in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff68a612f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff688de2e in g_cclosure_marshal_VOID__BOXEDv () from /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff688b244 in ?? () from /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff68a5a46 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff68a612f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#16 0x0000000000434d82 in check_child (data=0x753be0) at fr-process.c:937
#17 0x00007ffff65b76e3 in ?? () from /usr/lib/libglib-2.0.so.0
#18 0x00007ffff65b6c7a in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#19 0x00007ffff65b7020 in ?? () from /usr/lib/libglib-2.0.so.0
#20 0x00007ffff65b7342 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#21 0x00007ffff78c8787 in gtk_main () from /usr/lib/libgtk-x11-2.0.so.0
#22 0x0000000000411579 in main (argc=1, argv=0x7fffffffdb28) at main.c:322
(gdb) frame 1
#1  0x0000000000418e80 in dlg_open_with (window=0x6b1260, file_list=file_list@entry=0xcde960) at dlg-open-with.c:417
417     dlg-open-with.c: No such file or directory.
(gdb) print p
$1 = (GList *) 0xc7ef20
(gdb) print p->data
$2 = (gpointer) 0x0
(gdb) print app
$3 = (GAppInfo *) 0xcbe5b0
(gdb)
```

**Comment by monsta** [comment]
Thanks, fixed in https://github.com/mate-desktop/engrampa/commit/9323e93fcdcf6a65de3ee04494b9db6b44dcacf5.
