### ISSUE TITLE
Segmentation fault when trying to open .rar files

### ISSUE THREAD

**Issue by pabab** [mate-desktop/engrampa#95]
It happens with every .rar arhive I tried to open. GDB output gives this:

```
pabab@galadriel:/opt/engrampa$ gdb --args ./src/engrampa /home/pabab/Descargas/PROG2.rar 
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./src/engrampa...done.
(gdb) r
Starting program: /opt/engrampa/src/engrampa /home/pabab/Descargas/PROG2.rar
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffef9a0700 (LWP 14527)]
[New Thread 0x7fffeef71700 (LWP 14528)]
[New Thread 0x7fffee405700 (LWP 14529)]

(engrampa:14523): GLib-CRITICAL **: g_strchomp: assertion 'string != NULL' failed

Program received signal SIGSEGV, Segmentation fault.
parse_name_field (line=<optimized out>, rar_comm=0x9ed720) at fr-command-rar.c:155
155		if (*name_field == '/') {
(gdb) 
 ```

It seems to be a file-roller related problem. I'm usin unrar-free:

 ```
pabab@galadriel:~$ unrar --version
unrar 0.0.1
 ```

**Comment by monsta** [comment]
Which version of engrampa and which distro?

**Comment by pabab** [comment]
I'm using Engrampa 1.8.1, but the same error happens with git version (1.10.1) wich is the one I tried with GDB. I'm using Debian Jessie, kernel version 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux.

**Comment by monsta** [comment]
Can you post the full backtrace (```bt full```)? Install ```engrampa-dbg``` package before that to get more detailed info.

**Comment by pabab** [comment]
```
pabab@galadriel:~$ gdb --args /usr/bin/engrampa /home/pabab/Descargas/PROG2.rar
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/engrampa...Reading symbols from /usr/lib/debug/.build-id/26/d439f2eac7cac636ff5a93a39d43b826267fa8.debug...done.
done.
(gdb) r
Starting program: /usr/bin/engrampa /home/pabab/Descargas/PROG2.rar
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffef745700 (LWP 2363)]
[New Thread 0x7fffeed16700 (LWP 2364)]
[New Thread 0x7fffee1a6700 (LWP 2365)]

(engrampa:2359): GLib-CRITICAL **: g_strchomp: assertion 'string != NULL' failed

Program received signal SIGSEGV, Segmentation fault.
parse_name_field (line=<optimized out>, rar_comm=0xa42710) at fr-command-rar.c:154
154	fr-command-rar.c: No existe el fichero o el directorio.
(gdb) bt full
#0  parse_name_field (line=<optimized out>, rar_comm=0xa42710) at fr-command-rar.c:154
        name_field = 0x0
        fdata = 0xaa4b70
#1  0x000000000042bd6b in process_line (line=<optimized out>, data=<optimized out>) at fr-command-rar.c:218
        comm = 0xa42710
        rar_comm = <optimized out>
        fields = <optimized out>
        __FUNCTION__ = "process_line"
#2  0x0000000000432b8a in fr_channel_data_read (channel=channel@entry=0x6ffbe0) at fr-process.c:149
        line = 0xa3aad0 " PROG2/TP-Final/assets/fuentes/arial.ttf"
        length = 41
        terminator_pos = 40
#3  0x0000000000433b96 in check_child (data=0x6ffbc0) at fr-process.c:800
        process = 0x6ffbc0
        info = 0xa48300
        pid = <optimized out>
        status = 32767
        continue_process = <optimized out>
        channel_error = 0
        __FUNCTION__ = "check_child"
#4  0x00007ffff5569613 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#5  0x00007ffff5568b6d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007ffff5568f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007ffff5569272 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007ffff76bc597 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#9  0x000000000041126e in main (argc=1, argv=0x7fffffffe388) at main.c:331
        error = 0x0
        client = <optimized out>
        context = 0x679e60
```

**Comment by monsta** [comment]
Ok, try https://github.com/mate-desktop/engrampa/pull/96 - it might fix the issue.

**Comment by pabab** [comment]
Unfortunately it doesn't seem to fix the problem. The segfault doesn't occur now, but the file content list appears to be empty. Yet I can still list or extract the RAR file contents with de ```unrar``` command from the command line. Could it be related to the parsing of the ```unrar``` command output?

![pantallazo-3](https://cloud.githubusercontent.com/assets/440130/8804031/8e99d604-2fa0-11e5-9fcb-abc0813a1166.png)

**Comment by infirit** [comment]
Try removing unrar and install unarchiver (unar) and see if that handles it.

**Comment by pabab** [comment]
Removing unrar and install unarchiver efectively solved the problem. Thanks!

**Comment by infirit** [comment]
Ok, so it is something going on with the unrar and engrampa. Can you make the rar file available? Because all my rar files work fine with unrar.

**Comment by monsta** [comment]
The rar backend in engrampa (and file-roller) is designed to work with [non-free version of unrar](https://packages.debian.org/jessie/unrar). The [free version](https://packages.debian.org/jessie/unrar-free) that you use seems to use somewhat different formatting in its filelist output.

Personally, I wound't even use that free version. It's not developed since 2004 (see its [repo](http://cvs.gna.org/cvsweb/unrar/?cvsroot=unrar)), it has a number of major bugs (see [Debian bug tracker](https://bugs.debian.org/src:unrar-free))... Its description even states "Can't handle some archives in the RAR 3.0 format natively", which is ridiculous in year 2015. :smile:
